apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "172.22.0.2"
  bindPort: 6443
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"
  imagePullPolicy: IfNotPresent
  name: "k8s-control-plane"
  taints: null
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
kubernetesVersion: v1.35.0
networking:
  podSubnet: 10.244.0.0/16
etcd:
  local:
    extraArgs:
      - name: "heartbeat-interval"
        value: "500"
      - name: "election-timeout"
        value: "5000"
      - name: "snapshot-count"
        value: "10000"
